### ISSUE TITLE
Flask-BasicAuth==0.2.0

### ISSUE THREAD

**Issue by maartenk** [oharsta/ala#1]
Flask-BasicAuth package is still required in the [security module](https://github.com/oharsta/ala/blob/master/server/security/__init__.py)

**Comment by oharsta** [comment]
This is un-used code and is removed in https://github.com/oharsta/ala/commit/04cd4f69e62f11bdc81e49d7216f52b22fc53a74. Local everything worked as the library still existed in mine virtual env.
